// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Day5Data$Adventofcode2018 = require("./Day5Data.bs.js");

var str = "aA|bB|cC|dD|eE|fF|gG|hH|iI|jJ|kK|lL|mM|nN|oO|pP|qQ|rR|sS|tT|uU|vV|wW|xX|yY|zZ";

var str_backwards = str.split("").reverse().join("");

var polymer_regex = new RegExp("(" + (str + ("|" + (str_backwards + ")"))), "g");

var alphabet = /* array */[
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z"
];

function test_polymer(__x) {
  return polymer_regex.test(__x);
}

function case_insensitive_re(__x) {
  return new RegExp(__x, "gi");
}

function replace_letter(__x) {
  return (function (param) {
      return param.replace(__x, "");
    });
}

function replace_chain(param) {
  return param.replace(polymer_regex, "");
}

function remove_pairs(_input, _count) {
  while(true) {
    var count = _count;
    var input = _input;
    if (polymer_regex.test(input)) {
      _count = count + 1 | 0;
      _input = replace_chain(input);
      continue ;
    } else {
      console.log("Count: " + String(count));
      return input;
    }
  };
}

function find_shortest_polymer_chain(trimmed_chain) {
  return $$Array.fold_left((function (chain, cur) {
                var cur_chain = replace_letter(new RegExp(cur, "gi"))(trimmed_chain);
                var reacted_chain = remove_pairs(cur_chain, 0);
                var cur_len = reacted_chain.length;
                var chain_len = chain.length;
                var match = cur_len < chain_len;
                if (match) {
                  return reacted_chain;
                } else {
                  return chain;
                }
              }), trimmed_chain, alphabet);
}

console.log("Test data (1):");

console.log(remove_pairs(Day5Data$Adventofcode2018.test_input, 0) === "dabCBAcaDA");

console.log("Puzzle 1:");

console.log(remove_pairs(Day5Data$Adventofcode2018.input, 0).length);

console.log("Test data (2):");

console.log(find_shortest_polymer_chain(Day5Data$Adventofcode2018.test_input) === "daDA");

console.log("Puzzle 2:");

console.log(find_shortest_polymer_chain(Day5Data$Adventofcode2018.input).length);

exports.str = str;
exports.str_backwards = str_backwards;
exports.polymer_regex = polymer_regex;
exports.alphabet = alphabet;
exports.test_polymer = test_polymer;
exports.case_insensitive_re = case_insensitive_re;
exports.replace_letter = replace_letter;
exports.replace_chain = replace_chain;
exports.remove_pairs = remove_pairs;
exports.find_shortest_polymer_chain = find_shortest_polymer_chain;
/* str_backwards Not a pure module */
