[package]
name = "day-01"
version = "0.1.0"
authors = ["Tom Bremer <tom@tbremer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = '../utils' }
